"""add current_price to products

Revision ID: 4c845e8bc57b
Revises: fe2438a828c8
Create Date: 2026-09-22 17:59:02.328370

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c845e8bc57b"
down_revision: str | Sequence[str] | None = "fe2438a828c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("current_price", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "current_price")
    # ### end Alembic commands ###
