"""add state to tenants

Revision ID: 54caaf1d4c69
Revises: 4c845e8bc57b
Create Date: 2026-09-22 18:14:49.026006

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54caaf1d4c69"
down_revision: str | Sequence[str] | None = "4c845e8bc57b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("state", sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "state")
    # ### end Alembic commands ###
