"""add forecasts table

Revision ID: a3210b068e45
Revises: 1d6f193a3e83
Create Date: 2026-09-22 17:21:02.027837

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3210b068e45"
down_revision: str | Sequence[str] | None = "1d6f193a3e83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecasts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("point_estimate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("upper_bound", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("model_version", sa.Integer(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_forecasts_product_id"), "forecasts", ["product_id"], unique=False)
    op.create_index(
        "ix_forecasts_product_target",
        "forecasts",
        ["tenant_id", "product_id", "target_date"],
        unique=False,
    )
    op.create_index(op.f("ix_forecasts_tenant_id"), "forecasts", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_forecasts_tenant_id"), table_name="forecasts")
    op.drop_index("ix_forecasts_product_target", table_name="forecasts")
    op.drop_index(op.f("ix_forecasts_product_id"), table_name="forecasts")
    op.drop_table("forecasts")
    # ### end Alembic commands ###
